### ISSUE TITLE
Implement strict mode for flag parsing

### ISSUE THREAD

**Issue by Aweary** [bucaran/parsec#6]
In reference to https://github.com/flyjs/fly/issues/44. Strict flag parsing should either be the default, or an optional state for how flags are parsed, meaning that, for example, if  `-v` is an implemented flag, then invocations like `-v123` should throw an error instead of being parsed.

**Comment by bucaran** [comment]
@Aweary Sorry for the delay, but finally landed in @0.2.0.

This introduced a breaking change as the API was modified. Fortunately I found this improvement simplified how Parsec is used. 

```js
// ./app --msg=hi
Parsec
  .options("msg")
  .options("verbose", { default: false })
  .parse(process.argv)
```

The README also received a significant rewrite :pencil2:
