### ISSUE TITLE
make second arguments object

### ISSUE THREAD

**Issue by tunnckoCore** [bucaran/parsec#8]
that accepts the aliases (as minimist), not that array is confusing.

Then will be able to be used with 

https://github.com/jonschlinkert/minimist-plugins
https://github.com/jonschlinkert/minimist-events
https://github.com/jonschlinkert/minimist-expand
https://github.com/jonschlinkert/minimist-methods

that's ... what the.. ? nah.
```
// node ./index.js -s42
parse("secret", ["verbose", "V", { default: true }])
```

why verbose and v are true, when they are not given? there's no logic, they are "aliases" if they are in array, so.. why they are true.. nah.

**Comment by tunnckoCore** [comment]
And what about defining more aliases? E.g. `--global, -g` and `--verbose, -v` and `--version, -V`?

**Comment by bucaran** [comment]
I didn't know about minimist plugins! Very nice indeed. I will have a look and see if there is any way to make things compatible.

Now, it's all about taste don't you think? _I_ felt `minimist` API was too verbose (albeit being the leanest compared to nopt or commander):

```js
minimist(process.argv.slice(2), { alias: { 
  z: ["zoom", "zorro"],
  V: ["verbose"]
} }

// vs

parsec(["z", "zoom", "zorro"], ["V", "verbose"])
```

**Comment by bucaran** [comment]
> And what about defining more aliases? E.g. --global, -g and --verbose, -v and --version, -V? More array arguments? That's really uncomfortable.

You can define as many aliases as you need:

```js
parsec(["bar", "bor", "beer", "b", "B"])
```

**Comment by bucaran** [comment]
```js
// node ./index.js -s42
parse("secret", ["verbose", "V", { default: true }])
// result
{
  "s": 42,
  "secret": 42,
  "V": true,
  "verbose": true
}
```

> why verbose and v are true, when they are not given? there's no logic, they are "aliases" if they are in array, so.. why they are true.. nah.

`V` and `verbose` and `true` because that's their default value if you invoke `parsec` in that way. In this library "default" means: _I want this option (and its aliases) to have the specified **default** value if they are missing in `process.argv`.

**Comment by bucaran** [comment]
Closing due to lack of response from @tunnckoCore

**Comment by tunnckoCore** [comment]
What response you expect? It's not matter of my response, i said what i don't like. But yea, you're right, it's about taste.

> Now, it's all about taste don't you think?

**Comment by bucaran** [comment]
Thanks for your reply. I understand.
